// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// CardStrike keeps all secrets in .env.local (loaded by Next.js at runtime).
// The Prisma CLI doesn't read .env.local automatically, so load it here.
import { config as loadEnv } from "dotenv";
loadEnv({ path: [".env.local", ".env"] });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct/session connection (port 5432) for CLI schema operations.
    // The transaction pooler in DATABASE_URL (6543) hangs on DDL like `db push`.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
